[dependencies]
bevy = { version = "0.18.1", default-features = false, features = [
    "bevy_state",
    "std",
] }
bevy-tokio-tasks = "0.18.0"
bevy_ratatui = "0.11.1"
clap = { version = "4.6.1", features = ["derive", "env"] }
clap-help = "1.5.0"
colored = "3.1.1"
config = "0.15.22"
crossbeam-channel = "0.5.15"
dirs = "6.0.0"
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
shell-words = "1.1.1"
termimad = "0.34.1"
toml_edit = "0.25.11"
tokio = { version = "1.52.3", features = ["macros", "rt"] }
tokio-util = "0.7.18"
unicode-width = "0.2.2"
url = { version = "2.5.8", features = ["serde"] }
yoagent = { version = "0.8.0", features = ["openapi"] }

[features]
default = []

[lints.clippy]
diverging_sub_expression = "allow"
let_underscore_future = "allow"

[package]
categories = []
description = "Rimuru's Unique Skill, you know the one."
edition = "2024"
keywords = []
license = "MIT OR Apache-2.0"
name = "greatsage"
version = "0.0.2"

[profile.dev.package.backtrace]
opt-level = 3

[target.'cfg(not(target_os = "windows"))'.dependencies]
signal-hook = "0.4.4"
signal-hook-tokio = { version = "0.4.0", features = ["futures-v0_3"] }
